### PR TITLE
Admin invite - Invite users via model admin in the CMS

### PR DESCRIPTION
**Pull request by thomasbnielsen**
Adds the option to manage UserInvites via a ModelAdmin in the CMS, also adds the option to set a back_url.
Updated README

### CODE REVIEW

**Comment by thomasbnielsen** [comment]
Hi, can you please merge this?

**Comment by jsirish** [comment]
Hi @thomasbnielsen - sorry for the delay, we got swamped. I'm pulling down to test and will merge if all looks good. Thanks again!

**Comment by jsirish** [comment]
@thomasbnielsen looks like we have 5 failing tests, could you take a look at resolving those? Seem to be security related.

**Comment by muskie9** [comment]
I haven't been able to get tests running in my new workflow, however manual tests seem to work. I'm going to merge and we can continue updating/patching as needed.

**Pull request merged**
